language: node_js
node_js:
- stable
branches:
  only:
    - development
script:
- npm run coverage
notifications:
  email:
    recipients:
      - support@javathenutt.com
    on_success: never
    on_failure: always