language: node_js
node_js:
- stable
script:
- npm run coverage
after_success:
- npm run report-coverage
branches:
  only:
    - development
notifications:
  email:
    recipients:
      - support@javathenutt.com
    on_success: never
    on_failure: always